#include 'Totvs.ch'

/*/{Protheus.doc} SQLUpdate
(long_description)
@type user function
@author David
@since 09/02/2024
@version 1.0
/*/
User Function SQLUpdate(param_name)

    rpcSetEnv('99','01')

    cSQL := "UPDATE " + retSQLName("ZA1")
    cSQL += CRLF + "SET D_E_L_E_T_ = ' ' "
    cSQL += CRLF + "WHERE D_E_L_E_T_ = '*' ;"

    nSQL := TCSqlExec(cSQL)

        If  nSQL < 0
            FWAlertInfo(TCSqlError(),"Erro Update SQL")
        EndIf

    rpcClearEnv()

Return 
